var urls = [
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly001.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly002.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly003.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly006.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly013.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly054.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly109.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly183.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly241.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly256.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly312.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly328.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly405.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly559.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly611.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly660.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly666.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly706.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly750.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly761.html",
    "https://chillzonelore.github.io/ChillZoneLore/Anomaly953.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Aleksej-Orambo.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Chervovyj-Tuz.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Evgenij.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Kartoha.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Ketrin-Sweet.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Senichka.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Sofya-De-Lamar.html",
    "https://chillzonelore.github.io/ChillZoneLore/Civilian-Tin-D.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Darya-Daruak.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Elizaveta-Nesonkin.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Evgeniya-Hudozhnik.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Faj.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Kirill-E.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Krasnyj-Baron.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Mejshu.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Roman-V.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Shaurma.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-STA665.html",
    "https://chillzonelore.github.io/ChillZoneLore/Hunter-Vlad-Rouzgold.html",
    "https://deimost.ru/",
    "https://youtu.be/dQw4w9WgXcQ",

];
document.getElementById("random-link").addEventListener("click", function(){
    var url = urls[Math.floor(Math.random()*urls.length)]
  this.href = url;
});
